/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  react: [{ type: "autogenerated", dirName: "05-frameworks/01-react" }],
  vue2: [{ type: "autogenerated", dirName: "05-frameworks/02-vue2" }],
  vue3: [{ type: "autogenerated", dirName: "05-frameworks/03-vue3" }],
};

module.exports = sidebars;
